### PR TITLE
Master candidate2

### PR DESCRIPTION
**Pull request by smcelroy**
Sprint 3 Deliverable Current Build

### CODE REVIEW

**Comment by austin-cro** [comment]
code looks stable, will have another teammate double check

**Comment by CrystalG** [comment]
Looks good, with this I could finish the HistoryCards class now

**Comment by kalandr** [comment]
just make sure payday is working as intended and request looks in order

**Comment by smcelroy** [comment]
Yeah this branch has merged with your devKameron branch so it has the update payday method

**Pull request merged**
